<?php

declare(strict_types=1);

namespace Maguari\Server\Tests\Http;

use Maguari\Server\Tests\Support\TestEnvironment;
use PHPUnit\Framework\TestCase;
use Slim\Psr7\Factory\ServerRequestFactory;

/**
 * The dark theme is one external stylesheet: the Content-Security-Policy
 * blocks inline styles, so no template may use them.
 */
final class ThemeTest extends TestCase
{
    private const STYLESHEET = '/assets/maguari.css';

    public function testEveryPageLinksTheStylesheet(): void
    {
        $environment = new TestEnvironment();

        try {
            foreach (['/auth/login', '/nonexistent'] as $path) {
                $response = $environment->app()->handle((new ServerRequestFactory())->createServerRequest('GET', $path));
                $body = (string) $response->getBody();

                $this->assertStringContainsString('<link rel="stylesheet" href="' . self::STYLESHEET . '">', $body, $path);
                $this->assertStringContainsString('<script src="/assets/maguari.js" defer></script>', $body, $path);
                $this->assertStringContainsString("default-src 'self'", $response->getHeaderLine('Content-Security-Policy'));
                $this->assertStringNotContainsString('unsafe-inline', $response->getHeaderLine('Content-Security-Policy'));
            }
        } finally {
            $environment->cleanUp();
        }
    }

    public function testTheStylesheetIsDarkAndServedFromTheWebRoot(): void
    {
        $css = (string) file_get_contents(dirname(__DIR__, 2) . '/public' . self::STYLESHEET);

        $this->assertStringContainsString('color-scheme: dark;', $css);
        $this->assertStringContainsString('--background: #000000;', $css);
        // Table values such as project IDs, zones and timestamps never wrap.
        $this->assertMatchesRegularExpression('/\nth,\ntd \{[^}]*white-space: nowrap;/', $css);
    }

    public function testNoTemplateUsesInlineStyles(): void
    {
        foreach (glob(dirname(__DIR__, 2) . '/templates/*.php') ?: [] as $template) {
            $this->assertDoesNotMatchRegularExpression('/<style|\sstyle\s*=/i', (string) file_get_contents($template), basename($template));
        }
    }

    /**
     * A title attribute shows only on mouse hover, so details go through the
     * (i) icon of templates/info.php instead (design section 10.3).
     */
    public function testNoTemplateUsesTitleTooltips(): void
    {
        foreach (glob(dirname(__DIR__, 2) . '/templates/*.php') ?: [] as $template) {
            $this->assertDoesNotMatchRegularExpression('/\stitle\s*=/i', (string) file_get_contents($template), basename($template));
        }
    }

    /**
     * The Content-Security-Policy blocks inline scripts and event handler
     * attributes: scripts live in public/assets/.
     */
    public function testNoTemplateUsesInlineScripts(): void
    {
        foreach (glob(dirname(__DIR__, 2) . '/templates/*.php') ?: [] as $template) {
            $contents = (string) file_get_contents($template);
            $this->assertDoesNotMatchRegularExpression('/<script(?![^>]*\ssrc=)/i', $contents, basename($template));
            $this->assertDoesNotMatchRegularExpression('/\son[a-z]+\s*=/i', $contents, basename($template));
        }
    }

    /**
     * The details are a popover the icon opens without a script, and the
     * icon's "i" is generated by CSS, so copying a result never includes it.
     */
    public function testDetailsAreAPopoverAndTheIconHasNoText(): void
    {
        $partial = (string) file_get_contents(dirname(__DIR__, 2) . '/templates/info.php');
        $css = (string) file_get_contents(dirname(__DIR__, 2) . '/public/assets/maguari.css');

        $this->assertStringContainsString('aria-describedby="<?= $id ?>" popovertarget="<?= $id ?>"></button>', $partial);
        $this->assertStringContainsString('id="<?= $id ?>" popover role="tooltip">', $partial);
        $this->assertMatchesRegularExpression('/\.info-icon::before \{\s*content: "i";/', $css);
        $this->assertFileExists(dirname(__DIR__, 2) . '/public/assets/maguari.js');
    }
}
